name = "RayTrace"
uuid = "9441d024-97fe-11e8-2154-4d1b79854d30"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
